<template>
    <div>
        <h2>Design</h2>
        <h3>Three Factor Deployments</h3>
        <p>
            Monad uses convention to reduce the number of factors necessary for deploying an application
            from <a href="https://12factor.net/">twelve factors</a> to three.
        </p>
        The remaining factors are:
        <ol>
            <li>
                <strong>Codebase</strong> - A git repository.
            </li>
            <li>
                <strong>Dependencies</strong> - ECR image/s.
            </li>
            <li>
                <strong>Configuration</strong> - Environment variables.
            </li>
        </ol>

        <h3>Design Principles</h3>
        <h5>Single Binary</h5>
        <p>
            Monad is a single binary that can be used directly from developer machines and from CI/CD pipelines.
        </p>
        <h5>Git Ops</h5>
        <p>
            Monad uses conventions on top of git to allow all services on all branches to be deployed at any given
            time without conflict. All resources generated by Monad are tagged with git provenance data and all
            resource naming is likewise git interpolated.
        </p>
        <h5>OCI Artifact</h5>
        <p>
            The deployable artifact of Monad is an OCI compliant container image hosted on ECR.
        </p>
        <h5>No State File</h5>
        <p>
            AWS is the uncontested source of truth for AWS state. And so Monad uses the AWS Api for truth.
        </p>
        <p>
            Monad manages a deterministic set of shapes in AWS and does not need to grapple with arbitrary resource
            schema migration.
        </p>
        <h5>No Yaml</h5>
        <p>
            At run-time Monad derives it's configuration from available surrounding resources such as git,
            AWS caller identity and target AWS account information.
        </p>
        <h5>Minimal</h5>
        <p>
            Optionally provided configuration files are simply JSON request bodies documented extensively by AWS.
        </p>
        <h5>DRY</h5>
        <p>
            Optionally provided configuration is always passed through a templating engine containing a utilitarian
            set of variables designed for cross-account compatibility.
        </p>
        <h5>Least Privilege</h5>
        <p>
            Monad follows the principle of least privilege, ensuring all services are hermetically constrained by
            default. Adjusting permissions is easy, auditable, and granular to the needs of services and teams.
        </p>
    </div>
</template>

<style scoped>
div {
    margin: 0 15%;
}
</style>
