name: 'Docker Setup'
description: 'Sets up Docker with GHCR login, QEMU, Buildx, and containerd registry'

runs:
  using: "composite"
  steps:
    - name: GHCR Login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure Docker QEMU
      uses: docker/setup-qemu-action@v3

    - name: Configure Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Enable containerd registry
      uses: docker/setup-docker-action@v4
      with:
        daemon-config: |
          {
            "debug": true,
            "features": {
              "containerd-snapshotter": true
            }
          } 