name: 'Docker Setup'
description: 'Sets up Docker with GHCR login, QEMU, Buildx, and containerd registry'

inputs:
  token:
    required: true
    type: string
    description: 'GitHub token'

runs:
  using: "composite"
  steps:
    - name: GHCR Login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Configure Docker QEMU
      uses: docker/setup-qemu-action@v3

    - name: Configure Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest

    - name: Enable containerd registry
      uses: docker/setup-docker-action@v4
      with:
        version: latest
        daemon-config: |
          {
            "debug": true,
            "features": {
              "containerd-snapshotter": true
            }
          } 

    # - name: Export actions cache url details
    #   uses: actions/github-script@v7
    #   with:
    #     script: |
    #       core.exportVariable('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL'])
    #       core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])
    #       core.exportVariable('ACTIONS_RUNTIME_URL', process.env['ACTIONS_RUNTIME_URL'])