// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: proto/monad.proto

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeployRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUri      string                 `protobuf:"bytes,2,opt,name=imageUri,proto3" json:"imageUri,omitempty"` // Image URI
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_proto_monad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_proto_monad_proto_rawDescGZIP(), []int{0}
}

func (x *DeployRequest) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

type DeployResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUri      string                 `protobuf:"bytes,2,opt,name=imageUri,proto3" json:"imageUri,omitempty"`       // Image URI
	FunctionArn   string                 `protobuf:"bytes,3,opt,name=functionArn,proto3" json:"functionArn,omitempty"` // Function ARN
	PolicyArn     string                 `protobuf:"bytes,4,opt,name=policyArn,proto3" json:"policyArn,omitempty"`     // Policy ARN
	RoleArn       string                 `protobuf:"bytes,5,opt,name=roleArn,proto3" json:"roleArn,omitempty"`         // Role ARN
	EniRoleArn    string                 `protobuf:"bytes,6,opt,name=eniRoleArn,proto3" json:"eniRoleArn,omitempty"`   // ENI Role ARN
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`           // Status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResponse) Reset() {
	*x = DeployResponse{}
	mi := &file_proto_monad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResponse) ProtoMessage() {}

func (x *DeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResponse.ProtoReflect.Descriptor instead.
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return file_proto_monad_proto_rawDescGZIP(), []int{1}
}

func (x *DeployResponse) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

func (x *DeployResponse) GetFunctionArn() string {
	if x != nil {
		return x.FunctionArn
	}
	return ""
}

func (x *DeployResponse) GetPolicyArn() string {
	if x != nil {
		return x.PolicyArn
	}
	return ""
}

func (x *DeployResponse) GetRoleArn() string {
	if x != nil {
		return x.RoleArn
	}
	return ""
}

func (x *DeployResponse) GetEniRoleArn() string {
	if x != nil {
		return x.EniRoleArn
	}
	return ""
}

func (x *DeployResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DestroyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUri      string                 `protobuf:"bytes,2,opt,name=imageUri,proto3" json:"imageUri,omitempty"` // Image URI
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	mi := &file_proto_monad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_proto_monad_proto_rawDescGZIP(), []int{2}
}

func (x *DestroyRequest) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

type DestroyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionArn   string                 `protobuf:"bytes,2,opt,name=functionArn,proto3" json:"functionArn,omitempty"` // Function ARN
	PolicyArn     string                 `protobuf:"bytes,3,opt,name=policyArn,proto3" json:"policyArn,omitempty"`     // Policy ARN
	RoleArn       string                 `protobuf:"bytes,4,opt,name=roleArn,proto3" json:"roleArn,omitempty"`         // Role ARN
	EniRoleArn    string                 `protobuf:"bytes,5,opt,name=eniRoleArn,proto3" json:"eniRoleArn,omitempty"`   // ENI Role ARN
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`           // Status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyResponse) Reset() {
	*x = DestroyResponse{}
	mi := &file_proto_monad_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyResponse) ProtoMessage() {}

func (x *DestroyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monad_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyResponse.ProtoReflect.Descriptor instead.
func (*DestroyResponse) Descriptor() ([]byte, []int) {
	return file_proto_monad_proto_rawDescGZIP(), []int{3}
}

func (x *DestroyResponse) GetFunctionArn() string {
	if x != nil {
		return x.FunctionArn
	}
	return ""
}

func (x *DestroyResponse) GetPolicyArn() string {
	if x != nil {
		return x.PolicyArn
	}
	return ""
}

func (x *DestroyResponse) GetRoleArn() string {
	if x != nil {
		return x.RoleArn
	}
	return ""
}

func (x *DestroyResponse) GetEniRoleArn() string {
	if x != nil {
		return x.EniRoleArn
	}
	return ""
}

func (x *DestroyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_monad_proto protoreflect.FileDescriptor

var file_proto_monad_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x6e, 0x61, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x6e, 0x61, 0x64, 0x22, 0x2b, 0x0a, 0x0d, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x69, 0x22, 0xbe, 0x01, 0x0a, 0x0e, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x55, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x55, 0x72, 0x69, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x41, 0x72, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x72, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x41, 0x72, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x41, 0x72, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x41, 0x72,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x41, 0x72, 0x6e,
	0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6e, 0x69, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x72, 0x6e, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x69, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x72, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2c, 0x0a, 0x0e, 0x44, 0x65, 0x73, 0x74,
	0x72, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x55, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x55, 0x72, 0x69, 0x22, 0xa3, 0x01, 0x0a, 0x0f, 0x44, 0x65, 0x73, 0x74, 0x72,
	0x6f, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x72, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x41, 0x72, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x41, 0x72, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f,
	0x6c, 0x65, 0x41, 0x72, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x6c,
	0x65, 0x41, 0x72, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6e, 0x69, 0x52, 0x6f, 0x6c, 0x65, 0x41,
	0x72, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x69, 0x52, 0x6f, 0x6c,
	0x65, 0x41, 0x72, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0b, 0x5a, 0x09,
	0x70, 0x6b, 0x67, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_proto_monad_proto_rawDescOnce sync.Once
	file_proto_monad_proto_rawDescData []byte
)

func file_proto_monad_proto_rawDescGZIP() []byte {
	file_proto_monad_proto_rawDescOnce.Do(func() {
		file_proto_monad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_monad_proto_rawDesc), len(file_proto_monad_proto_rawDesc)))
	})
	return file_proto_monad_proto_rawDescData
}

var file_proto_monad_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_monad_proto_goTypes = []any{
	(*DeployRequest)(nil),   // 0: monad.DeployRequest
	(*DeployResponse)(nil),  // 1: monad.DeployResponse
	(*DestroyRequest)(nil),  // 2: monad.DestroyRequest
	(*DestroyResponse)(nil), // 3: monad.DestroyResponse
}
var file_proto_monad_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_monad_proto_init() }
func file_proto_monad_proto_init() {
	if File_proto_monad_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_monad_proto_rawDesc), len(file_proto_monad_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_monad_proto_goTypes,
		DependencyIndexes: file_proto_monad_proto_depIdxs,
		MessageInfos:      file_proto_monad_proto_msgTypes,
	}.Build()
	File_proto_monad_proto = out.File
	file_proto_monad_proto_goTypes = nil
	file_proto_monad_proto_depIdxs = nil
}
