"description": "Composite action for continuous integration"
"inputs":
  "action_branch":
    "default": "actionsOnly"
    "required": false
    "type": "string"
"name": "continuous integration"
"runs":
  "steps":
  - "name": "setup"
    "uses": "bkeane/monad-action@${{ inputs.action_branch }}"
    "with":
      "checkout": true
      "registry_id": "677771948337"
      "registry_region": "us-west-2"
      "role_arn": "arn:aws:iam::677771948337:role/monad-integration-oidc-role"
      "setup_docker": true
      "version": "latest"
  "using": "composite"
