volumes:
  bundle_cache:

services:
  test:
    image: ruby:3.2.3
    working_dir: /monad/e2e
    command: ["sh", "-c", "bundle install && bundle exec rspec -f d"]
    volumes:
      - ..:/monad
      - ~/.aws:/root/.aws
      - bundle_cache:/usr/local/bundle
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - FUNCTION_PATH=${FUNCTION_PATH}
      - SUBSTRATE_NAME=${SUBSTRATE_NAME}
      - SUBSTRATE_FEATURES=${SUBSTRATE_FEATURES}
    stdin_open: true
    tty: true
