"description": "Composite action to configure environment for build and push to the
  hub ECR registry"
"name": "hub config"
"runs":
  "steps":
  - "name": "setup"
    "uses": "bkeane/monad-action@main"
    "with":
      "registry_id": "677771948337"
      "registry_region": "us-west-2"
      "role_arn": "arn:aws:iam::677771948337:role/monad-hub-oidc-role"
      "setup_docker": true
      "version": "latest"
  - "name": "export"
    "uses": "actions/github-script@v7"
    "with":
      "script": |
        core.exportVariable('MONAD_BRANCH', '${{ github.head_ref || github.ref_name }}');
        core.exportVariable('MONAD_REGISTRY_ID', '677771948337');
        core.exportVariable('MONAD_REGISTRY_REGION', 'us-west-2');
        core.exportVariable('MONAD_SHA', '${{ github.event_name == "pull_request" && github.event.pull_request.head.sha || github.sha }}');
  "using": "composite"
