|
  "description": "Monad composite action for continuous deployment"
  "inputs":
    "account":
      "required": true
      "type": "string"
  "name": "monad continuous deployment"
  "runs":
    "steps":
    - "env":
        "ACCOUNT_ROLE_ARNS": "{\"dev\":\"arn:aws:iam::831926600600:role/monad-deployment-oidc-role\",\"prod\":\"arn:aws:iam::677771948337:role/monad-deployment-oidc-role\"}"
      "name": "validation"
      "outputs":
        "role_arn": "${{ steps.validation.outputs.role_arn }}"
      "uses": "actions/github-script@v7"
      "with":
        "script": "const account_role_arns = JSON.parse(process.env.ACCOUNT_ROLE_ARNS);\nconst
          given_account = '${{ inputs.account }}';\nconst valid_accounts = Object.keys(account_role_arns).join(',
          ');\n\nif (!(given_account in account_role_arns)) {\n  console.error('Invalid
          account name given: ' + given_account);\n  console.error('Valid accounts are:
          ' + valid_accounts);\n  core.setFailed('input validation failed');\n}\n            \ncore.setOutput('role_arn',
          account_role_arns[given_account]);\n"
    - "name": "setup"
      "uses": "bkeane/monad-action@main"
      "with":
        "checkout": true
        "registry_id": "677771948337"
        "registry_region": "us-west-2"
        "role_arn": "${{ needs.validation.outputs.role_arn }}"
        "setup_docker": false
        "version": "latest"
    - "name": "export"
      "uses": "actions/github-script@v7"
      "with":
        "script": |
          core.exportVariable('MONAD_REGISTRY_ID', '${{ inputs.registry_id }}');
          core.exportVariable('MONAD_REGISTRY_REGION', '${{ inputs.registry_region }}');
          core.exportVariable('MONAD_BRANCH', '${{ github.head_ref || github.ref_name }}');
          core.exportVariable('MONAD_SHA', '${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}');
    "using": "composite"
