"description": ""
"inputs":
  "account":
    "description": "name of the account"
    "required": true
    "type": "string"
  "region":
    "default": "us-west-2"
    "description": "region of the account"
    "required": false
    "type": "string"
  "stage":
    "description": "name of the stage"
    "required": true
    "type": "string"
"name": "setup stage"
"outputs":
  "role_arn":
    "description": "role arn for stage"
    "value": "${{ steps.validation.outputs.role_arn }}"
"runs":
  "steps":
  - "env":
      "RESOURCES": "{\"dev\":{\"deploy\":{\"permissions_boundary_arn\":\"arn:aws:iam::831926600600:policy/monad-deploy-permissions-boundary\",\"permissions_boundary_name\":\"monad-deploy-permissions-boundary\",\"policy_arn\":\"arn:aws:iam::831926600600:policy/monad-deploy-policy\",\"policy_name\":\"monad-deploy-policy\",\"role_arn\":\"arn:aws:iam::831926600600:role/monad-deploy-role\",\"role_name\":\"monad-deploy-role\"},\"e2e\":{\"permissions_boundary_arn\":\"arn:aws:iam::831926600600:policy/monad-e2e-permissions-boundary\",\"permissions_boundary_name\":\"monad-e2e-permissions-boundary\",\"policy_arn\":\"arn:aws:iam::831926600600:policy/monad-e2e-policy\",\"policy_name\":\"monad-e2e-policy\",\"role_arn\":\"arn:aws:iam::831926600600:role/monad-e2e-role\",\"role_name\":\"monad-e2e-role\"}},\"prod\":{\"build\":{\"permissions_boundary_arn\":\"arn:aws:iam::677771948337:policy/monad-ecr-mgmt-permissions-boundary\",\"permissions_boundary_name\":\"monad-ecr-mgmt-permissions-boundary\",\"policy_arn\":\"arn:aws:iam::677771948337:policy/monad-ecr-mgmt-policy\",\"policy_name\":\"monad-ecr-mgmt-policy\",\"role_arn\":\"arn:aws:iam::677771948337:role/monad-ecr-mgmt-role\",\"role_name\":\"monad-ecr-mgmt-role\"},\"deploy\":{\"permissions_boundary_arn\":\"arn:aws:iam::677771948337:policy/monad-deploy-permissions-boundary\",\"permissions_boundary_name\":\"monad-deploy-permissions-boundary\",\"policy_arn\":\"arn:aws:iam::677771948337:policy/monad-deploy-policy\",\"policy_name\":\"monad-deploy-policy\",\"role_arn\":\"arn:aws:iam::677771948337:role/monad-deploy-role\",\"role_name\":\"monad-deploy-role\"},\"e2e\":{\"permissions_boundary_arn\":\"arn:aws:iam::677771948337:policy/monad-e2e-permissions-boundary\",\"permissions_boundary_name\":\"monad-e2e-permissions-boundary\",\"policy_arn\":\"arn:aws:iam::677771948337:policy/monad-e2e-policy\",\"policy_name\":\"monad-e2e-policy\",\"role_arn\":\"arn:aws:iam::677771948337:role/monad-e2e-role\",\"role_name\":\"monad-e2e-role\"}}}"
    "id": "validation"
    "name": "validation"
    "uses": "actions/github-script@v7"
    "with":
      "script": |-
        const resources = JSON.parse(process.env.RESOURCES);
        const stage = '${{ inputs.stage }}';
        const account = '${{ inputs.account }}';
        // Validate resources[account] exists
        if (!(account in resources)) {
          console.error('Invalid account name given: ' + account);
          console.error('Valid accounts are: ' + Object.keys(resources).join(', '));
          process.exit(1);
        }
        // Validate resources[account][stage] exists
        if (!(stage in resources[account])) {
          console.error('Invalid stage name given: ' + stage);
          console.error('Valid stages for account ' + account + ' are: ' + Object.keys(resources[account]).join(', '));
          process.exit(1);
        }
        // Validate resources[account][stage].role_arn is not null
        if (resources[account][stage].role_arn == null) {
          console.error('No role arn found for account ' + account + ' and stage ' + stage);
          process.exit(1);
        }
        core.setOutput('role_arn', resources[account][stage].role_arn);
  - "id": "assume-role"
    "name": "assume role"
    "uses": "aws-actions/configure-aws-credentials@v2"
    "with":
      "aws-region": "${{ inputs.region }}"
      "role-session-name": "${{ inputs.account }}-${{ inputs.stage }}-session"
      "role-to-assume": "${{ steps.validation.outputs.role_arn }}"
  "using": "composite"
