"description": "Monad composite action for pre and post hooks in CI/CD"
"inputs":
  "account":
    "required": true
    "type": "string"
"name": "monad continuous hook action"
"outputs":
  "role_arn":
    "description": "The role arn for the given account"
    "value": "${{ steps.validation.outputs.role_arn }}"
"runs":
  "steps":
  - "env":
      "ACCOUNT_ROLE_ARNS": "{\"dev\":\"arn:aws:iam::831926600600:role/monad-hook-oidc-role\",\"prod\":\"arn:aws:iam::677771948337:role/monad-hook-oidc-role\"}"
    "id": "validation"
    "name": "validation"
    "uses": "actions/github-script@v7"
    "with":
      "script": |
        const account_role_arns = JSON.parse(process.env.ACCOUNT_ROLE_ARNS);
        const given_account = '${{ inputs.account }}';
        const valid_accounts = Object.keys(account_role_arns).join(', ');
        if (!(given_account in account_role_arns)) {
          console.error('Invalid account name given: ' + given_account);
          console.error('Valid accounts are: ' + valid_accounts);
          core.setFailed('input validation failed');
        }
        core.setOutput('role_arn', account_role_arns[given_account]);
  "using": "composite"
