name: build

# on:
#   push:
#     tags:
#       - 'v[0-9]+.[0-9]+.[0-9]+'

on:
  workflow_dispatch:
    inputs:
      stable:
        type: boolean
        default: false
        
permissions:
  contents: write
  packages: write

jobs:
  binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PERSONAL_AUTH_TOKEN: ${{ secrets.GR_PAT }}
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/ghcr-setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: build amd64
        run: |
          docker buildx build \
          --cache-to type=gha,mode=max,scope=${{ env.BRANCH_NAME }}-monad-amd64 \
          --cache-from type=gha,scope=${{ env.BRANCH_NAME }}-monad-amd64 \
          --platform linux/amd64 --load .
      - name: build arm64
        run: |
          docker buildx build \
          --cache-to type=gha,mode=max,scope=${{ env.BRANCH_NAME }}-monad-arm64 \
          --cache-from type=gha,scope=${{ env.BRANCH_NAME }}-monad-arm64 \
          --platform linux/arm64 --load .
      - name: publish
        run: |
          docker buildx build \
          --cache-from type=gha,scope=${{ env.BRANCH_NAME }}-monad-arm64 \
          --cache-from type=gha,scope=${{ env.BRANCH_NAME }}-monad-amd64 \
          -t ghcr.io/bkeane/monad:${{ github.ref_name }} \
          --platform linux/arm64,linux/amd64 --push .