name: deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup build context
        uses: ./.github/actions/integration
      - name: setup buildx
        uses: docker/setup-buildx-action@v3 
        with:
          version: v0.23.0
      - name: build
        run: |
          docker buildx build \
          --build-arg SOURCE_DATE_EPOCH=0 \
          --cache-to type=s3,region=us-west-2,bucket=kaixo-buildx-cache,name=echo,mode=max \
          --cache-from type=s3,region=us-west-2,bucket=kaixo-buildx-cache,name=echo \
          --output type=image,name=$(monad ecr tag --service echo),rewrite-timestamp=true,push=true \
          --platform linux/amd64,linux/arm64 \
          --file e2e/echo/Dockerfile \
          e2e/echo

  deployment:
    needs: integration
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        account: [dev, prod]
    environment:
      name: ${{ matrix.account }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup deployment context
        uses: ./.github/actions/deployment
        with:
          account: ${{ matrix.account }}
      - name: deploy
        working-directory: e2e/echo
        run: |
          monad deploy \
            --env file://.env.tmpl \
            --policy file://policy.json.tmpl \
            --rule file://rule.json.tmpl \
            --memory 256 \
            --disk 1024 \
            --timeout 10 \
            --api kaixo

  e2e:
    runs-on: ubuntu-24.04-arm
    needs: deployment
    env:
      TERM: xterm-color
      MONAD_SERVICE: echo
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        account: [dev, prod]
    environment:
      name: ${{ matrix.account }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup test context
        uses: ./.github/actions/hook
        with:
          account: ${{ matrix.account }}
      - name: setup shellspec
        uses: ./.github/actions/e2e
      - name: health
        working-directory: e2e
        run: shellspec --color spec/health/sigv4_spec.sh
      - name: lambda
        working-directory: e2e
        run: shellspec --color spec/config/lambda_spec.sh
      - name: apigatewayv2
        working-directory: e2e
        run: shellspec --color spec/config/apigatewayv2_spec.sh
      - name: eventbridge
        working-directory: e2e
        run: shellspec --color spec/config/eventbridge_spec.sh
