"env":
  "MONAD_BOUNDARY_POLICY": "monad-boundary-policy"
  "MONAD_BRANCH": "${{ github.head_ref || github.ref_name }}"
  "MONAD_REGISTRY_ID": "677771948337"
  "MONAD_REGISTRY_REGION": "us-west-2"
  "MONAD_SHA": "${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha
    || github.sha }}"
"jobs":
  "dev":
    "needs":
    - "echo"
    "outputs":
      "pass": "${{ steps.branch-check.outputs.pass }}"
      "roleArn": "${{ steps.branch-check.outputs.roleArn }}"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "Checkout"
      "uses": "actions/checkout@v4"
      "with":
        "fetch-depth": 1
    - "env":
        "ACCOUNT_BRANCHES": "*"
      "id": "branch-check"
      "uses": "actions/github-script@v7"
      "with":
        "script": |
          const branch = process.env.MONAD_BRANCH;
          const accepted = process.env.ACCOUNT_BRANCHES.split(',').map(b => b.trim());
          const pass = accepted.includes("*") || accepted.includes(branch)
          const roleArn = "arn:aws:iam::831926600600:role/monad-spoke-oidc-role"
          console.log("branch:", branch);
          console.log("accepted:", accepted);
          console.log("pass:", pass);
          console.log("roleArn:", roleArn);
          core.setOutput("pass", pass);
  "dev-deploy":
    "needs": "dev"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "deploy"
      "run": |
        echo "Deploying dev"
        echo "Pass: ${{ needs.dev.outputs.result.pass }}"
        echo "Role ARN: ${{ needs.dev.outputs.result.roleArn }}"
  "echo":
    "env":
      "MONAD_CHDIR": "e2e/echo"
      "MONAD_IMAGE": "bkeane/monad/echo"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "faux build"
      "run": "echo 'Building bkeane/monad/echo'"
  "prod":
    "needs":
    - "echo"
    "outputs":
      "pass": "${{ steps.branch-check.outputs.pass }}"
      "roleArn": "${{ steps.branch-check.outputs.roleArn }}"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "Checkout"
      "uses": "actions/checkout@v4"
      "with":
        "fetch-depth": 1
    - "env":
        "ACCOUNT_BRANCHES": "main"
      "id": "branch-check"
      "uses": "actions/github-script@v7"
      "with":
        "script": |
          const branch = process.env.MONAD_BRANCH;
          const accepted = process.env.ACCOUNT_BRANCHES.split(',').map(b => b.trim());
          const pass = accepted.includes("*") || accepted.includes(branch)
          const roleArn = "arn:aws:iam::677771948337:role/monad-spoke-oidc-role"
          console.log("branch:", branch);
          console.log("accepted:", accepted);
          console.log("pass:", pass);
          console.log("roleArn:", roleArn);
          core.setOutput("pass", pass);
  "prod-deploy":
    "needs": "prod"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "deploy"
      "run": |
        echo "Deploying prod"
        echo "Pass: ${{ needs.prod.outputs.result.pass }}"
        echo "Role ARN: ${{ needs.prod.outputs.result.roleArn }}"
"name": "Deploy"
"on":
  "pull_request": {}
  "push":
    "branches":
    - "main"
