"env":
  "MONAD_BOUNDARY_POLICY": "monad-boundary-policy"
  "MONAD_BRANCH": "${{ github.head_ref || github.ref_name }}"
  "MONAD_REGISTRY_ID": "677771948337"
  "MONAD_REGISTRY_REGION": "us-west-2"
  "MONAD_SHA": "${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha
    || github.sha }}"
"jobs":
  "deploy-echo":
    "env":
      "MONAD_API": "kaixo"
      "MONAD_CHDIR": "e2e/echo"
      "MONAD_DISK": "1024"
      "MONAD_ENV": "file://.env.tmpl"
      "MONAD_IMAGE": "bkeane/monad/echo"
      "MONAD_MEMORY": "256"
      "MONAD_POLICY": "file://policy.json.tmpl"
      "MONAD_RULE": "file://rule.json.tmpl"
      "MONAD_SERVICE": "echo"
      "MONAD_TIMEOUT": "10"
    "needs":
    - "release-echo"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "id": "setup-monad"
      "name": "Setup Monad"
      "uses": "bkeane/monad-action@main"
      "with":
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "${{ matrix.role_arn }}"
        "version": "latest"
    - "name": "deploy"
      "run": "monad deploy"
    "strategy":
      "matrix":
        "role_arn":
        - "arn:aws:iam::677771948337:role/monad-spoke-oidc-role"
        - "arn:aws:iam::831926600600:role/monad-spoke-oidc-role"
  "deploy-echo-oauth":
    "env":
      "MONAD_API": "kaixo"
      "MONAD_AUTH": "auth0"
      "MONAD_CHDIR": "e2e/echo"
      "MONAD_ENV": "file://.env.tmpl"
      "MONAD_IMAGE": "bkeane/monad/echo"
      "MONAD_POLICY": "file://policy.json.tmpl"
      "MONAD_RULE": "file://rule.json.tmpl"
      "MONAD_SERVICE": "echo-oauth"
    "needs":
    - "release-echo"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "id": "setup-monad"
      "name": "Setup Monad"
      "uses": "bkeane/monad-action@main"
      "with":
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "${{ matrix.role_arn }}"
        "version": "latest"
    - "name": "deploy"
      "run": "monad deploy"
    "strategy":
      "matrix":
        "role_arn":
        - "arn:aws:iam::677771948337:role/monad-spoke-oidc-role"
        - "arn:aws:iam::831926600600:role/monad-spoke-oidc-role"
  "deploy-echo-vpc":
    "env":
      "MONAD_API": "kaixo"
      "MONAD_CHDIR": "e2e/echo"
      "MONAD_ENV": "file://.env.tmpl"
      "MONAD_IMAGE": "bkeane/monad/echo"
      "MONAD_POLICY": "file://policy.json.tmpl"
      "MONAD_RULE": "file://rule.json.tmpl"
      "MONAD_SECURITY_GROUPS": "basic"
      "MONAD_SERVICE": "echo-vpc"
      "MONAD_SUBNETS": "private-a,private-b"
    "needs":
    - "release-echo"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "id": "setup-monad"
      "name": "Setup Monad"
      "uses": "bkeane/monad-action@main"
      "with":
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "${{ matrix.role_arn }}"
        "version": "latest"
    - "name": "deploy"
      "run": "monad deploy"
    "strategy":
      "matrix":
        "role_arn":
        - "arn:aws:iam::677771948337:role/monad-spoke-oidc-role"
        - "arn:aws:iam::831926600600:role/monad-spoke-oidc-role"
  "post-deploy-echo":
    "env":
      "MONAD_API": "kaixo"
      "MONAD_CHDIR": "e2e/echo"
      "MONAD_DISK": "1024"
      "MONAD_ENV": "file://.env.tmpl"
      "MONAD_IMAGE": "bkeane/monad/echo"
      "MONAD_MEMORY": "256"
      "MONAD_POLICY": "file://policy.json.tmpl"
      "MONAD_RULE": "file://rule.json.tmpl"
      "MONAD_SERVICE": "echo"
      "MONAD_TIMEOUT": "10"
    "needs": "deploy-echo"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "id": "setup-monad"
      "name": "Setup Monad"
      "uses": "bkeane/monad-action@main"
      "with":
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "${{ matrix.role_arn }}"
        "version": "latest"
    - "name": "health check"
      "run": "docker run -t --env-file <(env | grep -E '(MONAD|AWS)') -v $(pwd):/src
        ghcr.io/bkeane/spec:latest --chdir e2e"
    "strategy":
      "matrix":
        "role_arn":
        - "arn:aws:iam::677771948337:role/monad-spoke-oidc-role"
        - "arn:aws:iam::831926600600:role/monad-spoke-oidc-role"
  "post-deploy-echo-oauth":
    "env":
      "MONAD_API": "kaixo"
      "MONAD_AUTH": "auth0"
      "MONAD_CHDIR": "e2e/echo"
      "MONAD_ENV": "file://.env.tmpl"
      "MONAD_IMAGE": "bkeane/monad/echo"
      "MONAD_POLICY": "file://policy.json.tmpl"
      "MONAD_RULE": "file://rule.json.tmpl"
      "MONAD_SERVICE": "echo-oauth"
    "needs": "deploy-echo-oauth"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "id": "setup-monad"
      "name": "Setup Monad"
      "uses": "bkeane/monad-action@main"
      "with":
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "${{ matrix.role_arn }}"
        "version": "latest"
    - "name": "health check"
      "run": "docker run -t --env-file <(env | grep -E '(MONAD|AWS)') -v $(pwd):/src
        ghcr.io/bkeane/spec:latest --chdir e2e"
    "strategy":
      "matrix":
        "role_arn":
        - "arn:aws:iam::677771948337:role/monad-spoke-oidc-role"
        - "arn:aws:iam::831926600600:role/monad-spoke-oidc-role"
  "post-deploy-echo-vpc":
    "env":
      "MONAD_API": "kaixo"
      "MONAD_CHDIR": "e2e/echo"
      "MONAD_ENV": "file://.env.tmpl"
      "MONAD_IMAGE": "bkeane/monad/echo"
      "MONAD_POLICY": "file://policy.json.tmpl"
      "MONAD_RULE": "file://rule.json.tmpl"
      "MONAD_SECURITY_GROUPS": "basic"
      "MONAD_SERVICE": "echo-vpc"
      "MONAD_SUBNETS": "private-a,private-b"
    "needs": "deploy-echo-vpc"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "id": "setup-monad"
      "name": "Setup Monad"
      "uses": "bkeane/monad-action@main"
      "with":
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "${{ matrix.role_arn }}"
        "version": "latest"
    - "name": "health check"
      "run": "docker run -t --env-file <(env | grep -E '(MONAD|AWS)') -v $(pwd):/src
        ghcr.io/bkeane/spec:latest --chdir e2e"
    "strategy":
      "matrix":
        "role_arn":
        - "arn:aws:iam::677771948337:role/monad-spoke-oidc-role"
        - "arn:aws:iam::831926600600:role/monad-spoke-oidc-role"
  "release-echo":
    "env":
      "MONAD_CHDIR": "e2e/echo"
      "MONAD_IMAGE": "bkeane/monad/echo"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "id": "setup-monad"
      "name": "Setup Monad"
      "uses": "bkeane/monad-action@main"
      "with":
        "configure_for_build": true
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "arn:aws:iam::677771948337:role/monad-hub-oidc-role"
        "version": "latest"
    - "name": "bkeane/monad/echo:${{env.MONAD_BRANCH}}"
      "run": "monad compose | docker compose -f - build --push"
"name": "Deploy"
"on":
  "pull_request": {}
  "push":
    "branches":
    - "main"
