"env":
  "MONAD_BOUNDARY_POLICY": "monad-boundary-policy"
  "MONAD_BRANCH": "${{ github.head_ref || github.ref_name }}"
  "MONAD_REGISTRY_ID": "677771948337"
  "MONAD_REGISTRY_REGION": "us-west-2"
  "MONAD_SHA": "${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha
    || github.sha }}"
"jobs":
  "dev":
    "needs":
    - "echo"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "Checkout"
      "uses": "actions/checkout@v4"
      "with":
        "fetch-depth": 1
    - "env":
        "ACCOUNT_BRANCHES": "*"
      "uses": "actions/github-script@v7"
      "with":
        "script": |
          const { execSync } = require('child_process');
          const branch = execSync('git rev-parse --abbrev-ref HEAD').toString().trim();
          const accepted = process.env.ACCOUNT_BRANCHES.split(',').map(b => b.trim());
          console.log("branch:", branch);
          console.log("accepted:", accepted);
          return {
            pass: accepted.includes("*") || accepted.includes(branch),
            role-arn: "arn:aws:iam::123456789012:role/example-role"
          };
  "dev-post":
    "if": "fromJson(needs.dev.outputs.result).pass"
    "needs": "dev"
    "runs-on": "ubuntu-latest"
    "steps":
    - "id": "setup"
      "name": "setup"
      "uses": "bkeane/monad-action@main"
      "with":
        "configure_for_build": true
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "fromJson(needs.dev.outputs.result).role-arn"
        "version": "latest"
  "echo":
    "env":
      "MONAD_CHDIR": "e2e/echo"
      "MONAD_IMAGE": "bkeane/monad/echo"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "id": "setup"
      "name": "setup"
      "uses": "bkeane/monad-action@main"
      "with":
        "configure_for_build": true
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "arn:aws:iam::677771948337:role/monad-hub-oidc-role"
        "version": "latest"
    - "id": "release"
      "name": "release"
      "run": "monad compose | docker compose -f - build --push"
  "prod":
    "needs":
    - "echo"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "Checkout"
      "uses": "actions/checkout@v4"
      "with":
        "fetch-depth": 1
    - "env":
        "ACCOUNT_BRANCHES": "main"
      "uses": "actions/github-script@v7"
      "with":
        "script": |
          const { execSync } = require('child_process');
          const branch = execSync('git rev-parse --abbrev-ref HEAD').toString().trim();
          const accepted = process.env.ACCOUNT_BRANCHES.split(',').map(b => b.trim());
          console.log("branch:", branch);
          console.log("accepted:", accepted);
          return {
            pass: accepted.includes("*") || accepted.includes(branch),
            role-arn: "arn:aws:iam::123456789012:role/example-role"
          };
  "prod-post":
    "if": "fromJson(needs.prod.outputs.result).pass"
    "needs": "prod"
    "runs-on": "ubuntu-latest"
    "steps":
    - "id": "setup"
      "name": "setup"
      "uses": "bkeane/monad-action@main"
      "with":
        "configure_for_build": true
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "fromJson(needs.prod.outputs.result).role-arn"
        "version": "latest"
"name": "Deploy"
"on":
  "pull_request": {}
  "push":
    "branches":
    - "main"
