"env":
  "MONAD_BOUNDARY_POLICY": "monad-boundary-policy"
  "MONAD_BRANCH": "${{ github.head_ref || github.ref_name }}"
  "MONAD_REGISTRY_ID": "677771948337"
  "MONAD_REGISTRY_REGION": "us-west-2"
  "MONAD_SHA": "${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha
    || github.sha }}"
"jobs":
  "deploy-dev-echo":
    "env":
      "MONAD_API": "kaixo"
      "MONAD_CHDIR": "e2e/echo"
      "MONAD_DISK": "1024"
      "MONAD_ENV": "file://.env.tmpl"
      "MONAD_IMAGE": "bkeane/monad/echo"
      "MONAD_MEMORY": "256"
      "MONAD_POLICY": "file://policy.json.tmpl"
      "MONAD_RULE": "file://rule.json.tmpl"
      "MONAD_SERVICE": "echo"
      "MONAD_TIMEOUT": "10"
    "if": "needs.dev.outputs.pass == 'true'"
    "name": "deploy echo"
    "needs": "dev"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "setup"
      "uses": "bkeane/monad-action@main"
      "with":
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "${{ needs.dev.outputs.roleArn }}"
        "version": "latest"
    - "name": "deploy"
      "run": "monad deploy"
  "deploy-dev-echo-oauth":
    "env":
      "MONAD_API": "kaixo"
      "MONAD_AUTH": "auth0"
      "MONAD_CHDIR": "e2e/echo"
      "MONAD_ENV": "file://.env.tmpl"
      "MONAD_IMAGE": "bkeane/monad/echo"
      "MONAD_POLICY": "file://policy.json.tmpl"
      "MONAD_RULE": "file://rule.json.tmpl"
      "MONAD_SERVICE": "echo-oauth"
    "if": "needs.dev.outputs.pass == 'true'"
    "name": "deploy echo-oauth"
    "needs": "dev"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "setup"
      "uses": "bkeane/monad-action@main"
      "with":
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "${{ needs.dev.outputs.roleArn }}"
        "version": "latest"
    - "name": "deploy"
      "run": "monad deploy"
  "deploy-dev-echo-vpc":
    "env":
      "MONAD_API": "kaixo"
      "MONAD_CHDIR": "e2e/echo"
      "MONAD_ENV": "file://.env.tmpl"
      "MONAD_IMAGE": "bkeane/monad/echo"
      "MONAD_POLICY": "file://policy.json.tmpl"
      "MONAD_RULE": "file://rule.json.tmpl"
      "MONAD_SECURITY_GROUPS": "basic"
      "MONAD_SERVICE": "echo-vpc"
      "MONAD_SUBNETS": "private-a,private-b"
    "if": "needs.dev.outputs.pass == 'true'"
    "name": "deploy echo-vpc"
    "needs": "dev"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "setup"
      "uses": "bkeane/monad-action@main"
      "with":
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "${{ needs.dev.outputs.roleArn }}"
        "version": "latest"
    - "name": "deploy"
      "run": "monad deploy"
  "deploy-prod-echo":
    "env":
      "MONAD_API": "kaixo"
      "MONAD_CHDIR": "e2e/echo"
      "MONAD_DISK": "1024"
      "MONAD_ENV": "file://.env.tmpl"
      "MONAD_IMAGE": "bkeane/monad/echo"
      "MONAD_MEMORY": "256"
      "MONAD_POLICY": "file://policy.json.tmpl"
      "MONAD_RULE": "file://rule.json.tmpl"
      "MONAD_SERVICE": "echo"
      "MONAD_TIMEOUT": "10"
    "if": "needs.prod.outputs.pass == 'true'"
    "name": "deploy echo"
    "needs": "prod"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "setup"
      "uses": "bkeane/monad-action@main"
      "with":
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "${{ needs.prod.outputs.roleArn }}"
        "version": "latest"
    - "name": "deploy"
      "run": "monad deploy"
  "deploy-prod-echo-oauth":
    "env":
      "MONAD_API": "kaixo"
      "MONAD_AUTH": "auth0"
      "MONAD_CHDIR": "e2e/echo"
      "MONAD_ENV": "file://.env.tmpl"
      "MONAD_IMAGE": "bkeane/monad/echo"
      "MONAD_POLICY": "file://policy.json.tmpl"
      "MONAD_RULE": "file://rule.json.tmpl"
      "MONAD_SERVICE": "echo-oauth"
    "if": "needs.prod.outputs.pass == 'true'"
    "name": "deploy echo-oauth"
    "needs": "prod"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "setup"
      "uses": "bkeane/monad-action@main"
      "with":
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "${{ needs.prod.outputs.roleArn }}"
        "version": "latest"
    - "name": "deploy"
      "run": "monad deploy"
  "deploy-prod-echo-vpc":
    "env":
      "MONAD_API": "kaixo"
      "MONAD_CHDIR": "e2e/echo"
      "MONAD_ENV": "file://.env.tmpl"
      "MONAD_IMAGE": "bkeane/monad/echo"
      "MONAD_POLICY": "file://policy.json.tmpl"
      "MONAD_RULE": "file://rule.json.tmpl"
      "MONAD_SECURITY_GROUPS": "basic"
      "MONAD_SERVICE": "echo-vpc"
      "MONAD_SUBNETS": "private-a,private-b"
    "if": "needs.prod.outputs.pass == 'true'"
    "name": "deploy echo-vpc"
    "needs": "prod"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "setup"
      "uses": "bkeane/monad-action@main"
      "with":
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "${{ needs.prod.outputs.roleArn }}"
        "version": "latest"
    - "name": "deploy"
      "run": "monad deploy"
  "dev":
    "name": "dev"
    "needs":
    - "release-echo"
    "outputs":
      "pass": "${{ steps.branch-check.outputs.pass }}"
      "roleArn": "${{ steps.branch-check.outputs.roleArn }}"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "env":
        "ACCOUNT_BRANCHES": "*"
        "ACCOUNT_ROLE_ARN": "arn:aws:iam::831926600600:role/monad-spoke-oidc-role"
      "id": "branch-check"
      "uses": "actions/github-script@v7"
      "with":
        "script": |
          const branch = process.env.MONAD_BRANCH;
          const accepted = process.env.ACCOUNT_BRANCHES.split(',').map(b => b.trim());
          const pass = accepted.includes("*") || accepted.includes(branch)
          console.log("branch:", branch);
          console.log("accepted:", accepted);
          console.log("deploy:", pass);
          core.setOutput("pass", pass);
          core.setOutput("roleArn", process.env.ACCOUNT_ROLE_ARN);
  "prod":
    "name": "prod"
    "needs":
    - "release-echo"
    "outputs":
      "pass": "${{ steps.branch-check.outputs.pass }}"
      "roleArn": "${{ steps.branch-check.outputs.roleArn }}"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "env":
        "ACCOUNT_BRANCHES": "main"
        "ACCOUNT_ROLE_ARN": "arn:aws:iam::677771948337:role/monad-spoke-oidc-role"
      "id": "branch-check"
      "uses": "actions/github-script@v7"
      "with":
        "script": |
          const branch = process.env.MONAD_BRANCH;
          const accepted = process.env.ACCOUNT_BRANCHES.split(',').map(b => b.trim());
          const pass = accepted.includes("*") || accepted.includes(branch)
          console.log("branch:", branch);
          console.log("accepted:", accepted);
          console.log("deploy:", pass);
          core.setOutput("pass", pass);
          core.setOutput("roleArn", process.env.ACCOUNT_ROLE_ARN);
  "release-echo":
    "env":
      "MONAD_CHDIR": "e2e/echo"
      "MONAD_IMAGE": "bkeane/monad/echo"
    "name": "echo"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "id": "setup"
      "name": "setup"
      "uses": "bkeane/monad-action@main"
      "with":
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "arn:aws:iam::677771948337:role/monad-hub-oidc-role"
        "setup_docker": true
        "version": "latest"
    - "id": "release"
      "name": "release"
      "run": "monad compose | docker compose -f - build --push"
"name": "Deploy"
"on":
  "workflow_call": {}
