name: Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: test
        run: echo "Hello, test!"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    uses: ./.github/workflows/owl.yaml