name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: test
        run: echo "Hello, test!"
      - uses: ./.github/workflows/deploy_workflow.yaml
