name: destroy

on:
  pull_request_target:
    types:
      - closed

env:
  RELEVANT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
  RELEVANT_BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  destroy:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        account: [dev, prod]
    environment:
      name: ${{ matrix.account }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup stage
        uses: ./.github/actions/stages
        with:
          stage: deploy
          account: ${{ matrix.account }}

      - name: setup monad
        uses: bkeane/monad-action@v1
        with:
          ecr_registry_id: 677771948337
          ecr_registry_region: us-west-2

      - name: destroy
        run: |
          go run cmd/monad/main.go \
          --chdir e2e/echo \
          --branch ${{ env.RELEVANT_BRANCH }} \
          destroy

  untag:
    runs-on: ubuntu-latest
    needs: destroy
    permissions:
      contents: read
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup stage
        uses: ./.github/actions/stages
        with:
          stage: build
          account: prod

      - name: ecr login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: setup monad
        uses: bkeane/monad-action@v1
        with:
          ecr_registry_id: 677771948337
          ecr_registry_region: us-west-2

      - name: untag
        run: |
          go run cmd/monad/main.go \
          --chdir e2e/echo \
          --branch ${{ env.RELEVANT_BRANCH }} \
          ecr untag



