"env":
  "GH_TOKEN": "${{ secrets.GH_TOKEN }}"
  "MONAD_BOUNDARY_POLICY": "monad-boundary-policy"
  "MONAD_BRANCH": "${{ github.head_ref || github.ref_name }}"
  "MONAD_REGISTRY_ID": "677771948337"
  "MONAD_REGISTRY_REGION": "us-west-2"
  "MONAD_SHA": "${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha
    || github.sha }}"
"jobs":
  "destroy":
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "id": "setup-monad"
      "name": "Setup Monad"
      "uses": "bkeane/monad-action@main"
      "with":
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "${{ matrix.role_arn }}"
        "version": "latest"
    - "name": "Destroy echo"
      "run": "monad --chdir e2e/echo destroy"
    "strategy":
      "matrix":
        "role_arn":
        - "arn:aws:iam::831926600600:role/monad-spoke-oidc-role"
"name": "Destroy"
"on":
  "pull_request_target":
    "types":
    - "closed"
"untag":
  "permissions":
    "contents": "read"
    "id-token": "write"
  "runs-on": "ubuntu-latest"
  "steps":
  - "id": "setup-monad"
    "name": "Setup Monad"
    "uses": "bkeane/monad-action@main"
    "with":
      "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
      "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
      "role_arn": "arn:aws:iam::677771948337:role/monad-hub-oidc-role"
      "version": "latest"
  - "name": "Untag echo"
    "run": "monad --chdir e2e/echo ecr untag"
