"env":
  "MONAD_BOUNDARY_POLICY": "monad-boundary-policy"
  "MONAD_BRANCH": "${{ github.head_ref || github.ref_name }}"
  "MONAD_REGISTRY_ID": "677771948337"
  "MONAD_REGISTRY_REGION": "us-west-2"
  "MONAD_SHA": "${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha
    || github.sha }}"
"jobs":
  "destroy-echo":
    "env":
      "MONAD_API": "kaixo"
      "MONAD_CHDIR": "e2e/echo"
      "MONAD_ENV": "file://.env.tmpl"
      "MONAD_IMAGE": "bkeane/monad/echo"
      "MONAD_POLICY": "file://policy.json.tmpl"
      "MONAD_RULE": "file://rule.json.tmpl"
      "MONAD_SERVICE": "echo"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "id": "setup-monad"
      "name": "Setup Monad"
      "uses": "bkeane/monad-action@main"
      "with":
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "${{ matrix.role_arn }}"
        "version": "latest"
    - "name": "destroy"
      "run": "monad destroy"
    "strategy":
      "matrix":
        "role_arn":
        - "arn:aws:iam::677771948337:role/monad-spoke-oidc-role"
        - "arn:aws:iam::831926600600:role/monad-spoke-oidc-role"
  "destroy-echo-oauth":
    "env":
      "MONAD_API": "kaixo"
      "MONAD_AUTH": "auth0"
      "MONAD_CHDIR": "e2e/echo"
      "MONAD_ENV": "file://.env.tmpl"
      "MONAD_IMAGE": "bkeane/monad/echo"
      "MONAD_POLICY": "file://policy.json.tmpl"
      "MONAD_RULE": "file://rule.json.tmpl"
      "MONAD_SERVICE": "echo-oauth"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "id": "setup-monad"
      "name": "Setup Monad"
      "uses": "bkeane/monad-action@main"
      "with":
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "${{ matrix.role_arn }}"
        "version": "latest"
    - "name": "destroy"
      "run": "monad destroy"
    "strategy":
      "matrix":
        "role_arn":
        - "arn:aws:iam::677771948337:role/monad-spoke-oidc-role"
        - "arn:aws:iam::831926600600:role/monad-spoke-oidc-role"
  "destroy-echo-vpc":
    "env":
      "MONAD_API": "kaixo"
      "MONAD_CHDIR": "e2e/echo"
      "MONAD_ENV": "file://.env.tmpl"
      "MONAD_IMAGE": "bkeane/monad/echo"
      "MONAD_POLICY": "file://policy.json.tmpl"
      "MONAD_RULE": "file://rule.json.tmpl"
      "MONAD_SECURITY_GROUPS": "basic"
      "MONAD_SERVICE": "echo-vpc"
      "MONAD_SUBNETS": "private-a,private-b"
    "permissions":
      "contents": "read"
      "id-token": "write"
    "runs-on": "ubuntu-latest"
    "steps":
    - "id": "setup-monad"
      "name": "Setup Monad"
      "uses": "bkeane/monad-action@main"
      "with":
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "${{ matrix.role_arn }}"
        "version": "latest"
    - "name": "destroy"
      "run": "monad destroy"
    "strategy":
      "matrix":
        "role_arn":
        - "arn:aws:iam::677771948337:role/monad-spoke-oidc-role"
        - "arn:aws:iam::831926600600:role/monad-spoke-oidc-role"
  "untag-echo":
    "env":
      "MONAD_CHDIR": "e2e/echo"
      "MONAD_IMAGE": "bkeane/monad/echo"
    "needs":
    - "destroy-echo"
    - "destroy-echo-oauth"
    - "destroy-echo-vpc"
    "runs-on": "ubuntu-latest",
    "steps":
    - "id": "setup-monad"
      "name": "Setup Monad"
      "uses": "bkeane/monad-action@main"
      "with":
        "registry_id": "${{ env.MONAD_REGISTRY_ID }}"
        "registry_region": "${{ env.MONAD_REGISTRY_REGION }}"
        "role_arn": "arn:aws:iam::677771948337:role/monad-hub-oidc-role"
        "version": "latest"
    - "name": "untag"
      "run": "monad ecr untag"
"name": "Destroy"
"on":
  "pull_request_target":
    "types":
    - "closed"
