name: destroy

on:
  pull_request_target:
    types:
      - closed

env:
  RELEVANT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

jobs:
  destroy:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        account: [dev, prod]
    environment:
      name: ${{ matrix.account }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.RELEVANT_SHA }}

      - name: setup stage
        uses: ./.github/actions/stages
        with:
          stage: deploy
          account: ${{ matrix.account }}

      - name: setup monad
        uses: bkeane/monad-action@v0
        with:
          version: v0.1.4
          ecr_account_id: 677771948337
          ecr_account_region: us-west-2

      - name: destroy
        working-directory: e2e/echo
        run: monad destroy

  untag:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup stage
        uses: ./.github/actions/stages
        with:
          stage: build
          account: prod

      - name: setup monad
        uses: bkeane/monad-action@v0
        with:
          version: v0.1.4
          ecr_account_id: 677771948337
          ecr_account_region: us-west-2

      - name: untag
        working-directory: e2e/echo
        run: monad ecr untag



