name: GC

on:
  pull_request_target:
    types:
      - closed

jobs:
  down:
    uses: ./.github/workflows/down.yml
  untag:
    needs: down
    if: "!failure() && !cancelled()"
    uses: ./.github/workflows/untag.yml