name: QA

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # integration:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     id-token: write
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: setup
  #       uses: ./.github/actions/integration
  #     - name: build
  #       working-directory: e2e/echo
  #       run: |
  #         docker buildx build \
  #         -t $(monad ecr tag --service echo) \
  #         --platform linux/arm64,linux/amd64 --push .
  
  deployment:
    # needs: integration
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        account: [dev, prod]
    environment:
      name: ${{ matrix.account }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup
        uses: ./.github/actions/deployment
        with:
          account: ${{ matrix.account }}
      - name: deploy
        working-directory: e2e/echo
        run: |
          monad deploy \
          --service echo \
          --policy file://policy.json.tmpl \
          --rule file://rule.json.tmpl \
          --api kaixo
