name: QA

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: 1.24.0
      - name: test
        run: go test ./...
  latest:
    needs: test
    runs-on: self-hosted
    steps:
    - name: GHCR Login
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build latest image
        run: |
          docker build \
          -t ghcr.io/bkeane/monad:latest \
          --platform linux/amd64,linux/arm64 \
          --push .
  qa:
    needs: latest
    uses: ./.github/workflows/deploy.yml