name: QA

on:
  push:
    branches:
      - main
  pull_request:

# env:
#   BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - uses: actions/setup-go@v4
  #       with:
  #         go-version: 1.24.0
  #     - name: test
  #       run: go test ./...
  
  # monad:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - uses: ./.github/actions/ghcr-setup
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Build latest image
  #       run: |
  #         docker buildx build \
  #         --cache-to type=gha,mode=max,scope=${{ env.BRANCH_NAME }}-monad \
  #         --cache-from type=gha,scope=${{ env.BRANCH_NAME }}-monad \
  #         -t ghcr.io/bkeane/monad:latest \
  #         --platform linux/amd64,linux/arm64 \
  #         --push .
  
  echo:
    # needs: monad
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: build setup
        uses: ./.github/actions/ecr-setup
      - name: publish
        working-directory: e2e/echo
        run: |
          docker buildx build \
          --cache-to type=gha,mode=max,scope=${{ env.BRANCH_NAME }}-echo \
          --cache-from type=gha,scope=${{ env.BRANCH_NAME }}-echo \
          -t $(monad ecr tag --service echo) \
          --platform linux/amd64,linux/arm64 \
          --push .

  deploy:
    needs: echo
    uses: ./.github/workflows/up.yml