name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  packages: write

jobs:
  binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PERSONAL_AUTH_TOKEN: ${{ secrets.GR_PAT }}

  image:
    runs-on: ubuntu-latest
    steps:
        - name: GHCR Login
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Configure Docker QEMU
          uses: docker/setup-qemu-action@v3
        - name: Configure Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Enable containerd registry
          uses: docker/setup-docker-action@v4
          with:
            daemon-config: |
              {
                "debug": true,
                "features": {
                  "containerd-snapshotter": true
                }
              }
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Publish monad image
          run: |
            docker build \
            -t ghcr.io/bkeane/monad:${{ github.ref_name }} \
            -t ghcr.io/bkeane/monad:latest \
            --platform linux/amd64,linux/arm64 \
            --push .
