name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  packages: write

jobs:
  binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PERSONAL_AUTH_TOKEN: ${{ secrets.GR_PAT }}
  image:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: ./.github/actions/docker-setup
        - name: Publish monad image
          run: |
            docker build \
            -t ghcr.io/bkeane/monad:${{ github.ref_name }} \
            --platform linux/amd64,linux/arm64 \
            --push .
